version: 2
updates:
  - package-ecosystem: "cargo"
    directories: "/**/"
    schedule:
      interval: "monthly"
    exclude-paths:
      - "src/test/assets"
      - "vendor/**"
      - "src/*.js"
      - "src/test/helper.js"